---
- name: update web servers
  hosts: web1
  become: true

  tasks:
  - name: install and version tomcat
    copy:
      src: /var/lib/jenkins/workspace/my-pipeline/webapp/target/webapp.war
      dest: /home/ubuntu
